

all: build

codegen:
	node_modules/.bin/graph codegen subgraph.mainnet.yaml

build: codegen
	node_modules/.bin/graph build subgraph.mainnet.yaml

deploy: codegen
	node_modules/.bin/graph deploy --debug --node https://api.thegraph.com/deploy/ --ipfs https://api.thegraph.com/ipfs/ mcdexio/mcdex-vote-mainnet subgraph.mainnet.yaml
